### ISSUE TITLE
Tesseract OCR iOS release 4.0.0

### ISSUE THREAD

**Issue by kevincon** [gali8/Tesseract-OCR-iOS#123]
With the help of @BamX and @ws233, many new features and bugfixes have been added. Since these additions break our existing API, we should prepare for our next major CocoaPods release. Since the previous release was 3.4.0, this means the next major release will be 4.0.0 (following the rules of semantic versioning where the first number increments upon API-breaking changes).

Here are the outstanding issues with the repo on GitHub and my comments on each one. We should aim to resolve the unchecked issues before we mark the code for the 4.0.0 release:

- [x] #122 @BamX can you take a look at this since you added the sourceResolution property? We should resolve this before release.
- [x] #119 Check out the Stack Overflow I just posted that should help with how to resolve this issue. We should do this before release.
- [x] #111 This is not really an issue because it's just an artifact of not having released all the most recent code changes on CocoaPods. Releasing on CocoaPods will fix this issue.
- [x] #109 See the discussion in the issue about removing `characterBoxes`. We should resolve this before the release.
- [x] #85 I posted a comment on this issue regarding measuring test coverage. But I think we've done a good job with adding unit tests for most functionality, so I'm not too worried about this issue for the release.
- [x] #75 Based on the discussion there, I think we can add the hOCR method from https://github.com/clemenshelm/Tesseract-OCR-iOS/commit/15b5f8f2ae8c6325114623100243ef8168796ae8. That should be pretty easy, although I haven't heard back from @clemenshelm yet about why input name is set to "" in his method. It'd be good to understand why that's necessary (or maybe unnecessary) before adding the method. Also a unit test should be added to support it. We can do this before release.
- [x] #64 We've done a good job with documentation in the Wiki, but a few pages are still blank (tips for improving result, the homepage, etc.) so we should definitely finish those before the next release.
- [x] #52 I don't think exposing the _tesseract variable is a good idea, so we should try to work with @joaomvfsantos to understand what functionality he wants out of Tesseract that we're not currently providing. But this issue isn't critical to the release.
- [x] #42 The information from this issue should be added to the Wiki page for tips for improving the OCR result, and then it can be closed. This should be done before release.
- [x] #27 @ws233 and @BamX what do you think it would take to support OSX? The tesseract/leptonica libs have been compiled for i386 and x86_64 so I feel like it should be possible. But I don't think this is critical for our next release.
- [x] #130 Users are reporting the library crashing when they try to recognize on images captured from the camera, so we should fix this issue with `pixForImage` not considering orientation correctly.
- [x] We also want to wait until CocoaPods' next release, 0.36, because it adds support for building frameworks. Here's the pull request for the blog post about the release we're waiting on: CocoaPods/blog.cocoapods.org#59

Note that I've checked the boxes for items I don't think are critical to release, but I'm open to changing them.

**Comment by BamX** [comment]
And we are waiting for 0.36 release of CocoaPods, aren't we?

**Comment by kevincon** [comment]
Oh right, yes I'll add that to the list.

**Comment by BamX** [comment]
Could you rename issue with something like *Tesseract OCR iOS 4.0.0*? It looks strange referenced in related CocoaPods release pull-request.

**Comment by kevincon** [comment]
Sure thing, I didn't realize it would pop up on their screen. :)

**Comment by gali8** [comment]
@kevincon what about the 4.0 v? we are ready to release in cocoapods?
@BamX have you seen the first issue in the list above?

**Comment by kevincon** [comment]
@gali8 I haven't heard back from @ws233 or @BamX about pull request #126, which would fix #122 in the list above. Editing the Wiki for #64 is done enough for the 4.0.0 release. The last un-checked item is that we were waiting on the next version of CocoaPods to be released due to a new method we were using to build the Tesseract framework (embedded framework), but I think we are no longer using that method so it may be possible to release 4.0.0 without waiting for the next version of CocoaPods.

**Comment by gali8** [comment]
@kevincon  Ok! I hope that @BamX can fix #122 above.
Tomorrow I will release 4.0 on cocoapods.

**Comment by kevincon** [comment]
Whoa, hold on, why don't we just wait to release version 4.0.0 (remember, three numbers in the version from now on :) until #122 gets fixed? I'm sure @ws233 or @BamX will get a chance to look at it within the next day or so since we've reminded them tonight. I don't think it makes sense to release 4.0.0 when we're so close to fixing this last issue. I'll tag the 4.0.0 release on Github myself when it's ready and give you a heads-up so you can push the update to CocoaPods. Sound good?

**Comment by gali8** [comment]
Yep, LATER I will release 4.0.0 :)

**Comment by BamX** [comment]
Sorry for not answering. I have too much work now.
And I think we could not release 4.0.0 version before CocoaPods 0.36 release. Am I right?

**Comment by kevincon** [comment]
I think we thought that we needed CocoaPods 0.36 because it adds support for embedded frameworks, but we switched back from using an embedded framework to using a static framework again, right?

**Comment by ws233** [comment]
Hm. We still use embedded framework. But instead of dynamic one a static is used.
So I think we have to wait CocoaPods release. Or at least mention, which version should be used. As I know it's already moved to beta 2 stage.

**Comment by kevincon** [comment]
Oh okay, in that case I agree that we should continue to wait until the next CocoaPods release.

**Comment by kevincon** [comment]
I added another checkbox to the to-do list above for issue #130 since several users have been reporting problems with trying to use this library with images captured from the camera due to the orientation not being considered in our `pixForImage` method.

**Comment by ws233** [comment]
What if we add a few lines explaining how to write unit tests or change pod or travis CI configurations in contributing section?
For example, links to those official repo docs?

**Comment by kevincon** [comment]
Sure that makes sense, feel free to add those lines/links if you have time.

Although I think a higher priority issue is resolving #130. @ws233, do you know what the current status of that issue and its pull request is?

**Comment by ws233** [comment]
As I remember, @BamX did implement a new algorithm to redraw an image in a correct orientation. But it fails, while some unit test is run.

**Comment by lemak5** [comment]
Hi, 
Cocoapods version 0.36 has been released.
Do you think the new version of Tesseract will be available soon?
Thank you for Tesseract-OCR-iOS :)

**Comment by kevincon** [comment]
@lemak5 yes! We'll release v4.0.0 soon now that Cocoa Pods 0.36 has been released. There's just one thing that needs to be taken care of before we do...issue #130. I have final exams this week, so I won't be able to look into it until next week, but @BamX if you have some time before then, could you try to finish pull request #131?

**Comment by fnxpt** [comment]
@kevincon any update about this?

**Comment by kevincon** [comment]
@fnxpt I'm working on the last issue that needs to be resolved before we release. I promise we'll release version 4.0.0 by the end of this week. :)

**Comment by kevincon** [comment]
Finally it's ready! @gali8, I've tagged the 4.0.0 release on Github; can you please submit it to CocoaPods?

**Comment by gali8** [comment]
Done!
Thank you @kevincon

**Comment by kevincon** [comment]
Thanks, @gali8! Closing this issue now.
